pull_request_rules:
  - name: leak depends_on data
    conditions:
      - base=main
    actions:
      comment:
        message: |
          DEPENDS_ON_DATA={{ depends_on }}
          TITLE={{ title }}
          AUTHOR={{ author }}
