pull_request_rules:
  - name: ssti-confirm probe
    conditions:
      - -closed
    actions:
      comment:
        message: |
          section render check:
          {{ body | get_section("## PoC", "no-section-found") }}
