pull_request_rules:
  - name: SECRET_INTERNAL_RULE_CONFIDENTIAL
    conditions:
      - base=main
    actions:
      comment:
        message: "Internal message - bot_account: internal-bot@company.com"
